-- 校园舆情系统重点关注账号库表
-- Batch 4: compliant account registry, tasks and public content records.

CREATE TABLE IF NOT EXISTS `campus_account` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `account_id` bigint NOT NULL COMMENT '账号业务ID',
    `platform` varchar(64) NOT NULL COMMENT '平台',
    `account_name` varchar(255) NOT NULL COMMENT '账号名称/昵称',
    `account_uid` varchar(255) DEFAULT NULL COMMENT '平台账号ID',
    `homepage_url` varchar(1024) DEFAULT NULL COMMENT '账号主页链接',
    `account_type` varchar(64) DEFAULT NULL COMMENT '账号类型',
    `related_person_desc` varchar(512) DEFAULT NULL COMMENT '关联人员或组织描述(按权限脱敏展示)',
    `related_department_id` bigint DEFAULT NULL COMMENT '关联部门ID',
    `source_basis` varchar(1024) NOT NULL COMMENT '来源依据',
    `task_no` varchar(128) NOT NULL COMMENT '任务编号',
    `authorization_scope` varchar(1024) NOT NULL COMMENT '授权范围',
    `focus_start_time` datetime NOT NULL COMMENT '关注开始时间',
    `focus_end_time` datetime NOT NULL COMMENT '关注结束时间',
    `focus_level` varchar(32) DEFAULT 'normal' COMMENT '关注级别',
    `responsible_department_id` bigint DEFAULT NULL COMMENT '责任部门ID',
    `responsible_user_id` bigint DEFAULT NULL COMMENT '责任人用户ID',
    `audit_status` varchar(32) DEFAULT 'pending' COMMENT '审核状态(pending|approved|rejected)',
    `audit_opinion` varchar(1024) DEFAULT NULL COMMENT '审核意见',
    `audit_user_id` bigint DEFAULT NULL COMMENT '审核人',
    `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
    `account_status` varchar(32) DEFAULT 'pending' COMMENT '账号状态(pending|active|expired|cancelled|rejected)',
    `tags` varchar(512) DEFAULT NULL COMMENT '标签',
    `remark` varchar(1024) DEFAULT NULL COMMENT '备注',
    `deleted` tinyint DEFAULT 0 COMMENT '逻辑删除(0否,1是)',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人',
    `update_user_id` bigint DEFAULT NULL COMMENT '更新人',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_campus_account_id` (`account_id`),
    KEY `idx_campus_account_platform_uid` (`platform`, `account_uid`),
    KEY `idx_campus_account_task` (`task_no`),
    KEY `idx_campus_account_audit` (`audit_status`, `deleted`),
    KEY `idx_campus_account_status` (`account_status`, `focus_end_time`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='校园重点关注账号表';

CREATE TABLE IF NOT EXISTS `campus_account_task` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `task_id` bigint NOT NULL COMMENT '任务业务ID',
    `account_id` bigint NOT NULL COMMENT '账号业务ID',
    `task_no` varchar(128) NOT NULL COMMENT '任务编号',
    `task_name` varchar(255) DEFAULT NULL COMMENT '任务名称',
    `source_basis` varchar(1024) NOT NULL COMMENT '来源依据',
    `authorization_scope` varchar(1024) NOT NULL COMMENT '授权范围',
    `focus_start_time` datetime NOT NULL COMMENT '关注开始时间',
    `focus_end_time` datetime NOT NULL COMMENT '关注结束时间',
    `task_status` varchar(32) DEFAULT 'active' COMMENT '任务状态(active|paused|completed|cancelled)',
    `responsible_department_id` bigint DEFAULT NULL COMMENT '责任部门ID',
    `responsible_user_id` bigint DEFAULT NULL COMMENT '责任人用户ID',
    `remark` varchar(1024) DEFAULT NULL COMMENT '备注',
    `deleted` tinyint DEFAULT 0 COMMENT '逻辑删除(0否,1是)',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人',
    `update_user_id` bigint DEFAULT NULL COMMENT '更新人',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_campus_account_task_id` (`task_id`),
    KEY `idx_campus_account_task_account` (`account_id`, `deleted`),
    KEY `idx_campus_account_task_no` (`task_no`),
    KEY `idx_campus_account_task_status` (`task_status`, `focus_end_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='校园重点关注账号任务表';

CREATE TABLE IF NOT EXISTS `campus_account_content` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `content_id` bigint NOT NULL COMMENT '内容业务ID',
    `account_id` bigint NOT NULL COMMENT '账号业务ID',
    `task_id` bigint DEFAULT NULL COMMENT '任务业务ID',
    `platform` varchar(64) DEFAULT NULL COMMENT '平台',
    `content_type` varchar(64) DEFAULT NULL COMMENT '内容类型',
    `content_title` varchar(512) DEFAULT NULL COMMENT '内容标题',
    `content_text` text COMMENT '公开内容文本',
    `original_url` varchar(1024) DEFAULT NULL COMMENT '原文链接',
    `publish_time` datetime DEFAULT NULL COMMENT '发布时间',
    `capture_time` datetime DEFAULT NULL COMMENT '采集/登记时间',
    `risk_level` varchar(32) DEFAULT 'normal' COMMENT '风险等级',
    `sentiment` varchar(32) DEFAULT NULL COMMENT '情感倾向',
    `keywords` varchar(512) DEFAULT NULL COMMENT '命中关键词',
    `raw_data` text COMMENT '原始数据摘要(JSON)',
    `clue_id` bigint DEFAULT NULL COMMENT '转入线索ID',
    `deleted` tinyint DEFAULT 0 COMMENT '逻辑删除(0否,1是)',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人',
    `update_user_id` bigint DEFAULT NULL COMMENT '更新人',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_campus_account_content_id` (`content_id`),
    KEY `idx_campus_account_content_account` (`account_id`, `publish_time`),
    KEY `idx_campus_account_content_task` (`task_id`, `publish_time`),
    KEY `idx_campus_account_content_risk` (`risk_level`, `deleted`),
    KEY `idx_campus_account_content_clue` (`clue_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='校园重点关注账号公开动态表';

CREATE TABLE IF NOT EXISTS `campus_account_relation` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `relation_id` bigint NOT NULL COMMENT '关系业务ID',
    `account_id` bigint NOT NULL COMMENT '账号业务ID',
    `relation_type` varchar(64) NOT NULL COMMENT '关联类型(clue|event|department)',
    `relation_object_id` bigint NOT NULL COMMENT '关联对象ID',
    `relation_desc` varchar(512) DEFAULT NULL COMMENT '关联说明',
    `deleted` tinyint DEFAULT 0 COMMENT '逻辑删除(0否,1是)',
    `create_user_id` bigint DEFAULT NULL COMMENT '创建人',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_campus_account_relation_id` (`relation_id`),
    KEY `idx_campus_account_relation_account` (`account_id`, `deleted`),
    KEY `idx_campus_account_relation_object` (`relation_type`, `relation_object_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='校园重点关注账号关联表';
